#ifndef __HITMAC_CONF_H__
#define __HITMAC_CONF_H__
#include "contiki-conf.h"

#define HITMAC_PACKET_MAX_LEN MIN(127,PACKETBUF_SIZE)
#if HITMAC_CONF_DEFAULT_SCHEDULER_LENGTH == 18000 //15 minutes
/*each slot time length ms*/
#define HITMAC_CONF_DEFAULT_TIMESLOT_LENGTH (RTIMER_SECOND/20) //50ms
/*define asn increase time*/
#define HITMAC_ASN_PERIOD HITMAC_CONF_DEFAULT_TIMESLOT_LENGTH

/*define hitmac default scheduler*/
#define HITMAC_UPLOAD_LENGTH (256*3) //38.4s (256*3)
#define HITMAC_DOWNLOAD_LENGTH (6000) //5minutes (6000)
#define HITMAC_SLEEP_TIME_LENGTH  (HITMAC_CONF_DEFAULT_SCHEDULER_LENGTH-HITMAC_UPLOAD_LENGTH-HITMAC_DOWNLOAD_LENGTH)
#define HITMAC_TIME_LENGTH HITMAC_CONF_DEFAULT_SCHEDULER_LENGTH
#define HITMAC_EB_PERIOD  60//30 minutes 36000 time slot (CLOCK_SECOND*60*30)
#define HITMAC_SCAN_PERIOD  (CLOCK_SECOND*3)//30 minutes 36000 time slot (CLOCK_SECOND*60*30)



#define HITMAC_SYNC_TYPE 0
#define HITMAC_UPLOAD_TYPE 1
#define HITMAC_DOWNLOAD_TYPE 2
#define HITMAC_SLEEP_TYPE 3
#define HITMAC_UNKNOWN_TYPE 0xFFFFFFFF

#else
#error "NOT SUPPORT THIS SCHEDULER LENGTH"
#endif



#endif